# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = COGNAT
DESTDIR = ./x64/Release
CONFIG += release
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += ./GeneratedFiles/$(ConfigurationName)
OBJECTS_DIR += release
UI_DIR += ./GeneratedFiles
RCC_DIR += ./GeneratedFiles
win32:RC_FILE = COGNAT.rc
HEADERS += ./coloritem.h \
    ./database.h \
    ./domain.h \
    ./gbk.h \
    ./gene.h \
    ./graphicsscene.h \
    ./intergene.h \
    ./neighborhood.h \
    ./protein.h \
    ./stretchitem.h \
    ./taxon.h \
    ./taxonomymodel.h \
    ./bottomwidget.h \
    ./cognat.h \
    ./colorarchitecturesdialog.h \
    ./colorarchitecturesedit.h \
    ./treedelegate.h \
    ./topwidget.h \
    ./textbrowser.h \
    ./specifydatabasedialog.h \
    ./setvaluesdialog.h \
    ./settrustscorewidget.h \
    ./setradiusdialog.h \
    ./setminscorewidget.h \
    ./setminlengthwidget.h \
    ./setmaxoverlapwidget.h \
    ./searchgenesdialog.h \
    ./rightwidget.h \
    ./mainwidget.h \
    ./loadcolorschemeedit.h \
    ./loadcolorschemedialog.h
SOURCES += ./bottomwidget.cpp \
    ./cognat.cpp \
    ./colorarchitecturesdialog.cpp \
    ./colorarchitecturesedit.cpp \
    ./coloritem.cpp \
    ./database.cpp \
    ./domain.cpp \
    ./gbk.cpp \
    ./gene.cpp \
    ./graphicsscene.cpp \
    ./intergene.cpp \
    ./loadcolorschemedialog.cpp \
    ./loadcolorschemeedit.cpp \
    ./main.cpp \
    ./mainwidget.cpp \
    ./neighborhood.cpp \
    ./protein.cpp \
    ./rightwidget.cpp \
    ./searchgenesdialog.cpp \
    ./setmaxoverlapwidget.cpp \
    ./setminlengthwidget.cpp \
    ./setminscorewidget.cpp \
    ./setradiusdialog.cpp \
    ./settrustscorewidget.cpp \
    ./setvaluesdialog.cpp \
    ./specifydatabasedialog.cpp \
    ./stretchitem.cpp \
    ./taxon.cpp \
    ./taxonomymodel.cpp \
    ./textbrowser.cpp \
    ./topwidget.cpp \
    ./treedelegate.cpp
RESOURCES += COGNAT.qrc
