######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 10 15:13:37 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += bottomwidget.h \
           cognat.h \
           colorarchitecturesdialog.h \
           colorarchitecturesedit.h \
           coloritem.h \
           database.h \
           domain.h \
           gbk.h \
           gene.h \
           graphicsscene.h \
           intergene.h \
           loadcolorschemedialog.h \
           loadcolorschemeedit.h \
           mainwidget.h \
           neighborhood.h \
           protein.h \
           rightwidget.h \
           searchgenesdialog.h \
           setmaxoverlapwidget.h \
           setminlengthwidget.h \
           setminscorewidget.h \
           setradiusdialog.h \
           settrustscorewidget.h \
           setvaluesdialog.h \
           specifydatabasedialog.h \
           stretchitem.h \
           taxon.h \
           taxonomymodel.h \
           textbrowser.h \
           topwidget.h \
           treedelegate.h
SOURCES += bottomwidget.cpp \
           cognat.cpp \
           colorarchitecturesdialog.cpp \
           colorarchitecturesedit.cpp \
           coloritem.cpp \
           database.cpp \
           domain.cpp \
           gbk.cpp \
           gene.cpp \
           graphicsscene.cpp \
           intergene.cpp \
           loadcolorschemedialog.cpp \
           loadcolorschemeedit.cpp \
           main.cpp \
           mainwidget.cpp \
           neighborhood.cpp \
           protein.cpp \
           rightwidget.cpp \
           searchgenesdialog.cpp \
           setmaxoverlapwidget.cpp \
           setminlengthwidget.cpp \
           setminscorewidget.cpp \
           setradiusdialog.cpp \
           settrustscorewidget.cpp \
           setvaluesdialog.cpp \
           specifydatabasedialog.cpp \
           stretchitem.cpp \
           taxon.cpp \
           taxonomymodel.cpp \
           textbrowser.cpp \
           topwidget.cpp \
           treedelegate.cpp
RESOURCES += COGNAT.qrc
